# Generated by Django 4.2.11 on 2024-03-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_dish_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
